### ISSUE TITLE
Problem with bioblend?

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy-flavor-testing#12]
Latest tests on 18.09 branch of ansible-galaxy-extras failed when running bioblend test: https://travis-ci.org/galaxyproject/ansible-galaxy-extras/jobs/467924052
I wonder if it could be caused by https://github.com/galaxyproject/bioblend/commit/22fb3ef7aa6c3ea5d0aed13381428a55cf0529fc which would require some change to https://github.com/galaxyproject/galaxy-flavor-testing/blob/master/Makefile#L65
ping @nsoranzo maybe?

**Comment by nsoranzo** [comment]
Yes, that's the cause. I think you can replace `tox py27 -- -e 'test_download_dataset|test_download_history|test_export_and_download'` with `tox py27 -- -k 'not download_dataset and not download_history and not export_and_download'`

**Comment by abretaud** [comment]
Thanks! the change is in #13 
By the way do you plan a new bioblend release soon or not? (just wondering)

**Comment by nsoranzo** [comment]
bioblend v0.12.0 released!

**Comment by abretaud** [comment]
Coool thanks @nsoranzo!
