### ISSUE TITLE
Cannot write to ‘master.tar.gz’

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/galaxy-flavor-testing#3]
The Travis test on our Flavor fails without any real modification (README.md).

https://travis-ci.org/workflow4metabolomics/w4m-vm/builds/164635858#L741

```
$ make install
cd /home/galaxy && sudo su galaxy -c 'wget https://github.com/bgruening/bioblend/archive/master.tar.gz'
--2016-10-05 13:18:40--  https://github.com/bgruening/bioblend/archive/master.tar.gz
Resolving github.com (github.com)... 192.30.253.113
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/bgruening/bioblend/tar.gz/master [following]
--2016-10-05 13:18:41--  https://codeload.github.com/bgruening/bioblend/tar.gz/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘master.tar.gz’
    [ <=>                                   ] 0           --.-K/s   in 0s      
Cannot write to ‘master.tar.gz’ (Success).
make: *** [install] Error 3
The command "make install" failed and exited with 2 during .
Your build has been stopped.
```

Any idea?

Thanks

**Comment by bgruening** [comment]
Mh its working for me: https://travis-ci.org/bgruening/docker-galaxy-ngs-preprocessing

Can you rerun the test? Maybe this was a network error?

**Comment by pierrickrogermele** [comment]
I've got the same error on another branch of your project. I've re-run the build, and got the same error again.

**Comment by bgruening** [comment]
@pierrickrogermele @lecorguille oh great - so we have the same travis.yaml and it crashes randomly? 
I will trigger a few times for a build and see if I can reproduce it. 
It worked for you at some point isn't it?

**Comment by bgruening** [comment]
https://github.com/bgruening/docker-galaxy-epigenetics/pull/1 also working, I don't get it.

**Comment by lecorguille** [comment]
2 guys but the same repo.
So maybe, there is something with our project?
Is there some disk usage limitation in Travis?

**Comment by bgruening** [comment]
Mh, afaik the disc quota can vary between different VMs, sometime you can even get one which runs in a ramdisc. How many GB are you using approximately?

**Comment by lecorguille** [comment]
Our Docker images is rather big: 3.968 GB
We can try a `du -sh .` somewhere in the `.travis.yml` ?

**Comment by bgruening** [comment]
@lecorguille and maybe you can remove some tools in a branch and see what happens.
I will try to make the base image smaller for the next release if I find some time.

**Comment by pierrickrogermele** [comment]
I've run some commands.
The build is run inside /home/travis/build/workflow4metabolomics/w4m-vm, and the / point is as following:
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        30G   17G   13G  57%   /

**Comment by bgruening** [comment]
First time I have seen this: `https://travis-ci.org/bgruening/docker-galaxy-exome-seq/jobs/165581712#L639` but there seems to be a limit in space on travis. I was able to run out of discspace.

**Comment by bgruening** [comment]
It is indeed because of disc-space. https://travis-ci.org/bgruening/galaxy-rna-seq/builds/165854108#L696

Now I need to find a way to fix this :(

**Comment by lecorguille** [comment]
All green now 👍 
Thanks

**Comment by bgruening** [comment]
Perfect!
